services:
    stage-3-api:
        build:
            context: stage3/
            dockerfile: Dockerfile
        container_name: fecal-detection-stage1-2-api
        command: uvicorn app:app --host 0.0.0.0 --port 7137 --reload
        ports:
            - "7137:7137"
        environment:
            MODELS_DIR: /app/models
        restart: unless-stopped
