services:
    stage-3-api:
        build:
            context: api/stage3/
            dockerfile: Dockerfile
        container_name: fecal-detection-stage3-api
        command: uvicorn app:app --host 0.0.0.0 --port 7139 --reload
        ports:
            - "7139:7139"
        environment:
            MODELS_DIR: /app/models
        restart: unless-stopped
